Repository bsideproject/15_6_FE, pull requests merged in 2023-06, with the labels that each got.

#5 바텀 네비게이션 바 컴포넌트 제작
  package-lock.json
  package.json
  src/App.tsx
  src/assets/img/icn_badge_outline.svg
  src/assets/img/icn_badge_solid.svg
  src/assets/img/icn_home_outline.svg
  src/assets/img/icn_home_solid.svg
  src/assets/img/icn_list_outline.svg
  src/assets/img/icn_list_solid.svg
  src/assets/img/icn_user_outline.svg
  src/assets/img/icn_user_solid.svg
  src/assets/react.svg
  src/components/layout/BottomNavbar.tsx
  src/components/layout/DefaultLayout.tsx
  src/main.tsx
  src/pages/badge/index.tsx
  src/pages/home/index.tsx
  src/pages/nottodo/index.tsx
  src/pages/profile/index.tsx
  src/routes.tsx
  src/svg.d.ts
  src/utils/location.ts
  tailwind.config.js
  vite.config.ts
Labels: ✨feat, 💄style

#7 헤더 컴포넌트 구현
  src/assets/img/icn_back.svg
  src/assets/img/icn_logo.svg
  src/components/layout/DefaultLayout.tsx
  src/components/layout/Header.tsx
  src/constant/route.ts
  src/styles/global.scss
  src/utils/location.ts
  tailwind.config.js
Labels: ✨feat, 💄style

#9 네이버 클라우드 자동배포 로직 추가
  .dockerignore
  .github/workflows/ncp-deploy.yml
  Dockerfile
Labels: ✨feat

#12 [ chore ] https관련 nginx 설정 추가
  .github/workflows/ncp-deploy.yml
  Dockerfile
  nginx.conf
Labels: ✨feat

#13 [ chore ] 인증서 갱신용 설정 수정
  nginx.conf
Labels: ✨feat

#15 [ docs ] 리드미 수정
  Readme.md
Labels: 📝docs

#16 로그인 페이지 퍼블리싱
  .nvmrc
  src/assets/img/icn_apple.svg
  src/assets/img/icn_check_off.svg
  src/assets/img/icn_check_on.svg
  src/assets/img/icn_google.svg
  src/assets/img/icn_kakao.svg
  src/assets/img/img_login_content.svg
  src/components/buttons/SocialLoginButtons/AppleLoginButton.tsx
  src/components/buttons/SocialLoginButtons/BaseLoginButton.tsx
  src/components/buttons/SocialLoginButtons/GoogleLoginButton.tsx
  src/components/buttons/SocialLoginButtons/KakaoLoginButton.tsx
  src/constant/route.ts
  src/pages/login/index.tsx
  src/routes.tsx
  src/utils/location.ts
  src/utils/userAgent.ts
Labels: ✨feat

#18 10 스플래쉬 스크린 구현
  index.html
  package-lock.json
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/icon.png
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/vite.svg
  src/App.tsx
  src/assets/img/icn_logo_large.svg
  src/assets/img/icn_logo_medium.svg
  src/assets/img/icn_logo_small.svg
  src/assets/img/img_splash.svg
  src/assets/img/splash_logo.svg
  src/components/layout/BottomNavbar.tsx
  src/components/layout/SplashScreen.tsx
  src/styles/global.scss
  tailwind.config.js
  vite.config.ts
Labels: ✨feat

#20 [ feat ] 달력 컴포넌트 추가
  src/assets/img/icn_arrow.svg
  src/assets/img/icn_arrow_active.svg
  src/components/datepicker/Datepicker.tsx
  src/components/layout/SplashScreen.tsx
  src/utils/datepicker.ts
  tailwind.config.js
Labels: 🐛bug, ✨feat, 💄style

#25 서비스 이용약관 페이지 추가
  src/App.tsx
  src/components/layout/DefaultLayout.tsx
  src/constant/route.ts
  src/hooks/useEffectAfterMount.ts
  src/pages/signup/components/Terms.tsx
  src/pages/signup/index.tsx
  src/routes.tsx
  src/utils/location.ts
Labels: ✨feat

#27 [ feat ] 토글 버튼 컴포넌트 추가
  src/components/buttons/toggle/ToggleButton.tsx
Labels: ✨feat

#29 자동빌드 액션추가
  .github/workflows/auto-build.yml
  src/components/buttons/toggle/ToggleButton.tsx
  src/components/datepicker/Datepicker.tsx
  src/utils/datepicker.ts
Labels: 🐛bug, ✨feat

#30 [ fix ] 깃 액션 오류 수정
  .github/workflows/auto-build.yml
Labels: 🐛bug

#31 [ merge into main ] 빌드 버그 수정
  .github/workflows/auto-build.yml
  src/components/buttons/toggle/ToggleButton.tsx
  src/components/datepicker/Datepicker.tsx
  src/utils/datepicker.ts
Labels: 🐛bug

#32 스토리북 추가
  .eslintrc.cjs
  .github/workflows/storybook-deploy.yml
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/assets/img/icn_close.svg
  src/components/buttons/toggle/ToggleButton.stories.tsx
  src/components/buttons/toggle/ToggleButton.tsx
  src/components/datepicker/Datepicker.stories.tsx
  src/components/datepicker/Datepicker.tsx
  src/components/layout/BottomNavbar.stories.tsx
  src/components/layout/BottomNavbar.tsx
  src/components/layout/Header.stories.tsx
  src/components/layout/Header.tsx
  src/components/popup/Popup.stories.tsx
  src/components/popup/Popup.tsx
  src/components/popup/PopupGroup.tsx
Labels: ✨feat, 📝docs

#34 바텀 네비바 스타일 수정
  src/assets/img/icn_badge_outline.svg
  src/assets/img/icn_home_outline.svg
  src/assets/img/icn_list_outline.svg
  src/assets/img/icn_user_outline.svg
  src/components/layout/BottomNavbar.stories.tsx
  src/components/layout/BottomNavbar.tsx
  src/components/layout/DefaultLayout.tsx
  src/styles/global.scss
Labels: 💄style

#40 [ style ] 팝업 디자인 변경
  src/components/layout/BottomNavbar.tsx
  src/components/popup/Popup.stories.tsx
  src/components/popup/Popup.tsx
  src/components/popup/PopupGroup.tsx
  src/styles/global.scss
Labels: 💄style
